<?php session_start();
    /****************************************************************************
    * File Name: processOrder.php
    * Use-case: 
    * Author: Mike Young
    *
	* This page is where an order is finalized and the inventory is sold.
    *****************************************************************************/
	//var_dump($_POST);
	//the user must come to this page from processOrder.php. They will be posting a payment method.
	
	//connect
	$db = mysql_connect("studentdb-maria.gl.umbc.edu","hf28974","hf28974");
	if (!$db)
	{
		exit("Error - could not connect");
	}
	else
	{
		//echo ("Connected".'<br/>');
	}
	
	//select database
	$er = mysql_select_db("hf28974");
	if (!$er)
	{
		exit("Error - could not select");
	}
	else
	{
		//echo ("Selected".'<br/>');
	}
	
	switch ($_POST['instruction'])
	{
		case 'Finalize':
		{
			
			//update the payment method and status.
			$invID = $_POST['inv_num'];
			$pay = $_POST['paymentType'];
			$updateQuery = "UPDATE invoices SET payment_method='$pay', status='sold' WHERE invoice_num = '$invID';";
			//execute query
			$updateResult = mysql_query($updateQuery);
					
			if (!$updateResult)
			{
				print mysql_error();
				exit;
			}
			else
			{
				//echo ("update query run");
			}
			//At this point, the items are now sold. Update the quantity on hand and the sale volume for each item in this invoice.
			//get the item numbers
			$lineItemsQuery = "SELECT item_num, quantity FROM line_items WHERE invoice_num = '$invID';";
			$lineItemsResult = mysql_query($lineItemsQuery);
					
			if (!$lineItemsResult)
			{
				print mysql_error();
				exit;
			}
			else
			{
				//echo ("select query run");
			}
			
			for ($i = 0; $i < mysql_num_rows($lineItemsResult); $i++)
			{
				$itemNum = $line_items_row_array['item_num'];
				$sellQty = $line_items_row_array['quantity'];
				
				//we only want to show items that have been sold. 0 quantity sale means no sale occurred, so it is not worth stating.
				if($sellQty >= 1)
				{
					//decrease the quantity on hand and increase the sale volume of the item
					$line_items_row_array=mysql_fetch_array($lineItemsResult);
					//echo "sell qty: ".$sellQty."<br/>";
					$invUpdateQuery = "UPDATE inventory SET quantity = quantity - '$sellQty', sales_volume = sales_volume + '$sellQty' WHERE item_num = '$itemNum';";
					$invUpdateResult = mysql_query($invUpdateQuery);
					if (!$invUpdateResult)
					{
						print mysql_error();
						exit;
					}
					else
					{
						//echo ("update query run");
					}
				}
			}
		}
		break;
	}
	//once the invoice has been finalized, show the finalized document.
	$invID = $_POST['inv_num'];
	$invQuery = "SELECT invoices.invoice_num, invoices.order_timestamp, users.username, invoices.grand_total, invoices.payment_method FROM users INNER JOIN invoices ON invoices.buyer_num = users.user_num WHERE invoice_num = '$invID';";
	
	//execute query
	$invResult = mysql_query($invQuery);
			
	if (!$invResult)
	{
		print mysql_error();
		exit;
	}
	else
	{
		//echo ("select query run");
	}
	$invoice_row_array=mysql_fetch_array($invResult);
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>Finalize Order</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
		<!-- make sure the style sheet is accessible from all web pages -->
        <link href="../styleSheets/masterPageStyle.css" type="text/css" rel="Stylesheet" />
        <link href="../styleSheets/invoiceStyle.css" type="text/css" rel="Stylesheet" />
    </head>
    <body>
		<!-- the page header will be a separate file  -->
	<?php
		//include('../pageHeaderScripts/header.php');
    ?>
        <div id="content">
            <!-- This table will be generated by selecting all records from invoices where the buyer's ID matches the user's -->
			<table class="invoiceHeaderTable">
				<tr>
					<td>
						Invoice ID<br/>
						<span style="font-weight:bold;"><?php echo $invoice_row_array['invoice_num'] ?></span>
					</td>
					<td>
						Customer ID<br/>
						<?php echo $invoice_row_array['buyer_num'] ?>
					</td>
					<td>
						Time Placed<br/>
						<?php echo $invoice_row_array['order_timestamp'] ?>
					</td>
					<td>
						Buyer<br/>
						<?php
							$buyNum = $invoice_row_array['buyer_num'];
							$buyerQuery = "SELECT username FROM users WHERE user_num = '$buyNum';";

							//execute query
							$buyerResult = mysql_query($buyerQuery);
									
							if (!$buyerResult)
							{
								print mysql_error();
								exit;
							}
							else
							{
								//echo ("select query run");
							}
							$buyer_row_array = mysql_fetch_array($buyerResult);
							echo $buyer_row_array['username'];
						?>
					</td>
					<td>
						Seller<br/>
						<?php
							$sellNum = $invoice_row_array['seller_num'];
							$sellerQuery = "SELECT username FROM users WHERE user_num = '$sellNum';";

							//execute query
							$sellerResult = mysql_query($sellerQuery);
									
							if (!$sellerResult)
							{
								print mysql_error();
								exit;
							}
							else
							{
								//echo ("select query run");
							}
							$seller_row_array = mysql_fetch_array($sellerResult);
							echo $seller_row_array['username'];
						?>
					</td>
					<td>
						Payment Method<br/>
						<?php echo $invoice_row_array['payment_method'] ?>
					</td>
				</tr>
			</table>
			<table class="lineItemsTable">
				<tr>
					<td>
						SUPPLIER
					</td>
					<td>
						PRODUCT
					</td>
					<td>
						NAME
					</td>
					<td>
						QUANTITY
					</td>
					<td>
						UNIT PRICE
					</td>
					<td>
						EXTENDED PRICE
					</td>
				</tr>
				<?php
					//get the item numbers and quantities
					$lineItemsQuery = "SELECT inventory.item_num, inventory.supplier, inventory.product, inventory.item_name, inventory.sell_price, line_items.quantity FROM line_items INNER JOIN inventory ON inventory.item_num = line_items.item_num WHERE line_items.invoice_num = '$invID';";
					//execute query
					$lineItemsResult = mysql_query($lineItemsQuery);
							
					if (!$lineItemsResult)
					{
						print mysql_error();
						exit;
					}
					else
					{
						//echo ("select query run");
					}
					
					//this variable calculates the subtotal of the invoice.
					$subtotal = 0.00;
					for ($i = 0; $i < mysql_num_rows($lineItemsResult); $i++)
					{
						//hold data for the line items
						$line_items_row_array=mysql_fetch_array($lineItemsResult);
				?>
				<tr>
					<td>
						<?php echo $line_items_row_array['supplier'] ?>
					</td>
					<td>
						<?php echo $line_items_row_array['product'] ?>
					</td>
					<td>
						<?php echo $line_items_row_array['item_name'] ?>
					</td>
					<td>
						<?php echo $line_items_row_array['quantity'] ?>
					</td>
					<td>
						$<?php echo $line_items_row_array['sell_price'] ?>
					</td>
					<td>
						$<?php
							$unitPrx = $line_items_row_array['sell_price'];
							//echo $unitPrx;
							$qty = $line_items_row_array['quantity'];
							//echo $qty;
							$extPrx = $unitPrx * $qty;
							echo number_format($extPrx, 2);
							//increase the running subtotal after displaying each item
							$subtotal += $extPrx;
						?>
					</td>
				</tr>
				<?php
					}
					mysql_close();
				?>
			</table>
			<table class="subtotalTable">
				<tr>
					<td>
						Subtotal
					</td>
					<td>
						$<?php echo $subtotal; ?>
					</td>
				</tr>
				<tr>
					<td>
						Sale Tax
					</td>
					<td>
						$<?php
							//the tax can sometimes result in more than 2 decimal places. Therefore, specify precision of 2 decimal places
							$tax = round(($subtotal * 0.06), 2);
							echo $tax; 
						?>
					</td>
				</tr>
				<tr>
					<td>
						Total Sale
					</td>
					<td>
						$<?php
							$grandTotal = $subtotal + $tax;
							echo round($grandTotal, 2);
						?>
					</td>
				</tr>
			</table>
            <a href="pendingOrders.php">Back to orders</a>
        </div>
		<!-- Like the header, the footer will be present on ALL pages -->
	<?php
		//include('../pageFooterScripts/footer.php');
    ?>
    </body>
</html>