<?php session_start();
    /****************************************************************************
    * File Name: processOrder.php
    * Use-case: 
    * Author: Mike Young
    *
	* This page shows a the seller all orders waiting to be processed.
    *****************************************************************************/
	//connect
	$db = mysql_connect("studentdb-maria.gl.umbc.edu","hf28974","hf28974");
	if (!$db)
	{
		exit("Error - could not connect");
	}
	else
	{
		//echo ("Connected".'<br/>');
	}
	
	//select database
	$er = mysql_select_db("hf28974");
	if (!$er)
	{
		exit("Error - could not select");
	}
	else
	{
		//echo ("Selected".'<br/>');
	}
	
	$sell = $_SESSION['user_num'];
	$invoiceQuery = "SELECT invoices.invoice_num, invoices.order_timestamp, users.username, invoices.payment_method FROM users INNER JOIN invoices ON invoices.buyer_num = users.user_num WHERE status = 'pending' AND seller_num = '$sell' ORDER BY -order_timestamp;";
	
	//execute query
	$invoiceResult = mysql_query($invoiceQuery);
			
	if (!$invoiceResult)
	{
		print mysql_error();
		exit;
	}
	else
	{
		//echo ("select query run");
	}
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>Pending Orders</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
		<!-- make sure the style sheet is accessible from all web pages -->
        <link href="../styleSheets/masterPageStyle.css" type="text/css" rel="Stylesheet" />
        <link href="../styleSheets/invoiceStyle.css" type="text/css" rel="Stylesheet" />
		<script type="text/javascript" src="../validationScripts/invoiceValidation.js"></script>
    </head>
    <body>
		<!-- the page header will be a separate file  -->
	<?php
		include('../pageHeaderScripts/header.php');
    ?>
        <div id="content">
            <!-- This table will be generated by selecting all records from Invoices where the buyer's ID matches the user's -->
            <!-- The invoice IDs will link to the invoices -->
            <table class="invoiceHeaderTable">
				<tr>
					<td>
						Invoice ID
					</td>
					<td>
						Time Placed
					</td>
					<td>
						Buyer
					</td>
					<td>
						Payment Method
					</td>
				</tr>
				<?php
					
					for ($i = 0; $i < mysql_num_rows($invoiceResult); $i++)
					{
						$invoice_row_array=mysql_fetch_array($invoiceResult);
						?>
							<tr>
								<td>
									<a href="processOrder.php?inv_num=<?php echo $invoice_row_array['invoice_num'] ?>"><?php echo $invoice_row_array['invoice_num'] ?></a>
								</td>
								<td>
									<?php echo $invoice_row_array['order_timestamp'] ?>
								</td>
								<td>
									<?php echo $invoice_row_array['username']; ?>
								</td>
								<td>
									<?php echo $invoice_row_array['payment_method'] ?>
								</td>
							</tr>
						<?php
					}
					mysql_close();
				?>
            </table>
            <a href="../home/index.php">Back to Home</a>
            <!-- If the user is a seller, an additional table will display all of their sold invoices -->
        </div>
		<!-- Like the header, the footer will be present on ALL pages -->
	<?php
		include('../pageFooterScripts/footer.php');
    ?>
    </body>
</html>