<?php session_start();
    /****************************************************************************
    * File Name: invoiceListView.php
    * Use-case: 
    * Author: Mike Young
    *
	* This page displays the user's invoices they have purchased and those which are still pending.
    *****************************************************************************/
	//connect
	$db = mysql_connect("studentdb-maria.gl.umbc.edu","hf28974","hf28974");
	if (!$db)
	{
		exit("Error - could not connect");
	}
	else
	{
		//echo ("Connected".'<br/>');
	}
	
	//select database
	$er = mysql_select_db("hf28974");
	if (!$er)
	{
		exit("Error - could not select");
	}
	else
	{
		//echo ("Selected".'<br/>');
	}
	
	//var_dump($_POST);
	switch($_POST['instruction'])
	{
		case 'Cancel':
		{
			$invID = $_POST['inv_num'];
			$updateQuery = "UPDATE invoices SET status='cancelled' WHERE invoice_num = '$invID';";
			//execute query
			$updateResult = mysql_query($updateQuery);
					
			if (!$updateResult)
			{
				print mysql_error();
				exit;
			}
			else
			{
				//echo ("update query run");
			}
		}
		break;
	}
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>Invoice List</title>
		<!-- make sure the style sheet is accessible from all web pages -->
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <link href="../styleSheets/masterPageStyle.css" type="text/css" rel="Stylesheet" />
		<script type="text/javascript" src="../validationScripts/confirmCancel.js" >
		</script>
    </head>
    <body>
		<!-- the page header will be a separate file  -->
	<?php
		include('../pageHeaderScripts/header.php');
    ?>
        <div id="content">
			<table>
				<tr>
					<td class="invoiceList">
						<!-- This table will be generated by selecting all records from Invoices where the buyer's ID matches the user's -->
						Purchased Invoices<br/>
						<!-- buyer ID is this user's ID -->
						Finalized<br/>
						<table>
							<tr>
								<td>
									Invoice ID
								</td>
								<td>
									Seller
								</td>
								<td>
									Transaction Date
								</td>
								<td>
									Payment Type
								</td>
							</tr>
							<?php
								//get the invoice number, time ordered, seller's username, invoice total, and payment method
								$uid = $_SESSION['user_num'];
								$headerQuery = "SELECT invoices.invoice_num, invoices.order_timestamp, users.username, invoices.grand_total, invoices.payment_method FROM users INNER JOIN invoices ON users.user_num = invoices.seller_num WHERE invoices.buyer_num = '$uid' AND status = 'sold' ORDER BY -invoices.order_timestamp;";
								//run the statement
								$headerResult = mysql_query($headerQuery);

								if (!$headerResult)
								{
									print mysql_error();
									exit;
								}
								else
								{
									//echo ("checkQuery run<br/>");
								}
								
								for ($i = 0; $i < mysql_num_rows($headerResult); $i++)
								{
									//store the resulting query
									$header_row_array = mysql_fetch_array($headerResult);
							?>
							<tr>
								<td>
									<a href="invoiceView.php?inv_num=<?php echo $header_row_array['invoice_num']; ?>"><?php echo $header_row_array['invoice_num']; ?></a>
								</td>
								<td>
									<?php
										echo $header_row_array['username'];
									?>
								</td>
								<td>
									<?php
										echo $header_row_array['order_timestamp'];
									?>
								</td>
								<td>
									<?php
										echo $header_row_array['payment_method'];
									?>
								</td>
							</tr>
							<?php
								}
							?>
						</table><br />
						Pending
						<table>
							<tr>
								<td>
									Invoice ID
								</td>
								<td>
									Seller
								</td>
								<td>
									Transaction Date
								</td>
								<td>
									Payment Type
								</td>
								<td>
									Action
								</td>
							</tr>
							<?php
								//get the invoice number, time ordered, seller's username, invoice total, and payment method
								$uid = $_SESSION['user_num'];
								$headerQuery = "SELECT invoices.invoice_num, invoices.order_timestamp, users.username, invoices.grand_total, invoices.payment_method FROM users INNER JOIN invoices ON users.user_num = invoices.seller_num WHERE invoices.buyer_num = '$uid' AND status = 'pending' ORDER BY -invoices.order_timestamp;";
								//run the statement
								$headerResult = mysql_query($headerQuery);

								if (!$headerResult)
								{
									print mysql_error();
									exit;
								}
								else
								{
									//echo ("checkQuery run<br/>");
								}
								
								for ($i = 0; $i < mysql_num_rows($headerResult); $i++)
								{
									//store the resulting query
									$header_row_array = mysql_fetch_array($headerResult);
							?>
							<tr>
								<form action="invoiceListView.php" method="post" onsubmit="return confirmCancel();">
									<td>
										<a href="invoiceView.php?inv_num=<?php echo $header_row_array['invoice_num']; ?>"><?php echo $header_row_array['invoice_num']; ?></a>
									</td>
									<td>
										<?php
											echo $header_row_array['username'];
										?>
									</td>
									<td>
										<?php
											echo $header_row_array['order_timestamp'];
										?>
									</td>
									<td>
										<?php
											echo $header_row_array['payment_method'];
										?>
									</td>
									<td>
											<input name="inv_num" value="<?php echo $header_row_array['invoice_num']; ?>" type="hidden" />
											<input name="instruction" value="Cancel" type="submit" />
									</td>
								</form>
							</tr>
							<?php
								}
							?>
						</table>
						<!-- The invoice IDs will link to the invoices -->
						<a href="accountView.php">Back to My Account</a>

						<!-- If the user is a seller, an additional table will display all of their sold invoices -->

					</td>
					<?php
						if ($_SESSION['account_type'] == 'seller')
						{
					?>
					<td class="invoiceList">
						Sold Invoices<br/>
						<!-- seller ID is this user's ID -->
						Finalized<br/>
						<table>
							<tr>
								<td>
									Invoice ID
								</td>
								<td>
									Buyer
								</td>
								<td>
									Transaction Date
								</td>
								<td>
									Payment Type
								</td>
							</tr>
							<?php
								//get the invoice number, time ordered, buyer's username, invoice total, and payment method
								$uid = $_SESSION['user_num'];
								$headerQuery = "SELECT invoices.invoice_num, invoices.order_timestamp, users.username, invoices.grand_total, invoices.payment_method FROM users INNER JOIN invoices ON users.user_num = invoices.buyer_num WHERE invoices.seller_num = '$uid' AND status = 'sold' ORDER BY -invoices.order_timestamp;";
								//run the statement
								$headerResult = mysql_query($headerQuery);

								if (!$headerResult)
								{
									print mysql_error();
									exit;
								}
								else
								{
									//echo ("checkQuery run<br/>");
								}
								
								for ($i = 0; $i < mysql_num_rows($headerResult); $i++)
								{
									//store the resulting query
									$header_row_array = mysql_fetch_array($headerResult);
							?>
							<tr>
								<td>
									<a href="invoiceView.php?inv_num=<?php echo $header_row_array['invoice_num']; ?>"><?php echo $header_row_array['invoice_num']; ?></a>
								</td>
								<td>
									<?php
										echo $header_row_array['username'];
									?>
								</td>
								<td>
									<?php
										echo $header_row_array['order_timestamp'];
									?>
								</td>
								<td>
									<?php
										echo $header_row_array['payment_method'];
									?>
								</td>
							</tr>
							<?php
								}
							?>
						</table><br />
					</td>
					<?php
						}
					?>
				</tr>
			</table>
        </div>
		<!-- Like the header, the footer will be present on ALL pages -->
	<?php
		include('../pageFooterScripts/footer.php');
    ?>
    </body>
</html>